<?php

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://www.vidswatcher.com/?page=videos");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = "User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:63.0) Gecko/20100101 Firefox/63.0";
$headers[] = "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8";
$headers[] = "Accept-Language: id,en-US;q=0.7,en;q=0.3";
$headers[] = "Referer: https://www.vidswatcher.com/?page=videos&vid=13";
$headers[] = "Connection: keep-alive";
$headers[] = "Cookie: _ga=GA1.2.1251253335.1542319669; _gid=GA1.2.1656805331.1542319669; AccExist=royhul255; AutoLogin=ses_user=royhul255&ses_hash=3b73d86f187a63d72087ba12eabe2b76;";
$headers[] = "Upgrade-Insecure-Requests: 1";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}

curl_close ($ch);
preg_match_all('/onclick="opensite((.*?));/', $result, $matches);
//echo var_dump($matches);
foreach ($matches['1'] as $value) 

{
	$v = str_replace("('", "", $value);
	$v = str_replace("')", "", $v);
	echo $v."\n";
}
?>